# Generated by Django 4.0.1 on 2022-01-19 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote', models.TextField()),
                ('quote_by', models.CharField(default='Praveen Vishwakarma', max_length=200, null=True)),
            ],
        ),
    ]
