# Generated by Django 4.0.3 on 2022-04-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignupmodel',
            name='user_account',
        ),
        migrations.RemoveField(
            model_name='usersignupmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usersignupmodel',
            name='user_balance',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='usersignupmodel',
            name='user_email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
