# Generated by Django 4.0.3 on 2022-04-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_usersignupmodel_user_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignupmodel',
            name='user_balance',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
